language: android
sudo: true

components:
    - tools
    - platform-tools
    - tools

    - build-tools-26.0.0
    - android-26

    - extra-google-m2repository
    - extra-android-m2repository


licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
